---
title: "SFB Experiment 2"
author: "Pam"
date: "06.10.2020"
output: html_document
---

```{r setup, include=FALSE}
# load packages----
library(plyr)
library(RTconflict)
x <- c("tidyverse","cowplot","lme4","afex")
lapply(x, FUN = function(X) {
  do.call("require", list(X)) 
})
knitr::opts_chunk$set(echo = TRUE)
```

# Reanalysis of Experiment 1: Does slope of PWI predict magnitude of interference effect?
```{r prepare data set, include = FALSE}
# Reanalysis of Experiment 1 individual differences----
setwd("/Users/pamelafuhrmeister/Documents/Work/Postdoc/SFB/Experiment_1/Data")

df <- read.csv("Results_PWI_EEG_20200526.csv", sep=";")

df$Span_Mean_c <- df$Span_Mean-mean(df$Span_Mean)
df$CTET_Hit_c <- df$CTET_Hit-mean(df$CTET_Hit)
df$Slope_Simon_c <- df$Slope_Simon-mean(df$Slope_Simon)
df$Slope_Flanker_c <- df$Slope_Flanker-mean(df$Slope_Flanker)

summary(df)
df$Accuracy <- as.factor(as.character(df$Response_Trial))
df$Participant_ID <- as.factor(as.character(df$Participant_ID))

df$Trial.position <- as.numeric(as.character(df$Picture_ID_Multipic))
df$Picture  <- as.factor(as.character(df$Trigger_Picture ))

df$Comment <- as.factor(as.character(df$Response_Trial))
df$Condition <- as.factor(as.character(df$Trigger_Condition))
df$Condition <- plyr::mapvalues(df$Condition, from = c("101", "102", "103","104","105"), to = c("baseline","phono.rel", "phono.unr", "sem.rel", "sem.unr"))
df$Condition <- as.factor(as.character(df$Condition))

nrow(df)

table(df$Response_Trial)

df2b <- df[df$Response_Trial=="correct",]
nrow(df2b)
nrow(df2b)-nrow(df)

nrow(df) - nrow(df2b)

# maybe include? comment out for now
# df4 <- df3[df3$RT>599,]
# nrow(df3) - nrow(df4)
# nrow(df4)
# summary(df4)
# 
# plot(density(df4$RT))
# qqnorm(df4$RT)
# hist(df4$RT)
# boxplot(df4$RT)
# 
# 
# df5 <- df4[df4$RT<2301,] 
# nrow(df4) - nrow(df5)
```

```{r, include = FALSE}
# library(MASS)
# ginv2 <- function(x) #Function to inverse Matrix (see Schad et al., https://arxiv.org/abs/1807.10451)
#   fractions(provideDimnames(ginv(x),base=dimnames(x)[2:1]))
# 
# #define contrast matrix
# contrasts(df5$Condition)
# hM <- cbind(c.gen_int1=c(F1=-1,F2=0, F3 = 1, F4 = 0,  F5 =0), c.gen_int2=c(F1=-1,F2=0, F3 = 0, F4 = 0,  F5 =1), c.phon =c(F1=0,F2=1, F3 = -1, F4 = 0,  F5 =0),c.sem= c(F1=0,F2=0, F3 = 0, F4 = 1,  F5 =-1))
# cM <- ginv2(t(hM))
# contrasts(df5$Condition) <- cM
# contrasts(df5$Condition)
# 
# m0 <- lmer(RT~(Condition)+(1|Picture)+(1| Participant_ID), data=df5)
# mat_trt <- model.matrix(m0)
# head(mat_trt)
# df5$c.gen.int1 <- mat_trt[,2]
# df5$c.gen.int2 <- mat_trt[,3]
# df5$c.phon<- mat_trt[,4]
# df5$c.sem <- mat_trt[,5]
# 
# detach(package:MASS)
# #check means
# m <- lm(RT~c.gen.int1+c.gen.int2+c.phon+c.sem, data=df5)
# summary(m)
# 
# m1 <- lmer(log(RT)~(c.gen.int1+c.gen.int2+c.phon+c.sem)*(Slope_Flanker_c+Slope_Simon_c+CTET_Hit_c+Span_Mean_c) +(1+c.gen.int1+c.gen.int2*Slope_Simon_c+c.phon+c.sem||Picture)+(1+c.gen.int1+c.gen.int2+c.phon+c.sem||Participant_ID), data = df5)
# summary(m1)
# 
# m1b <- lmer(log(RT)~(c.gen.int1 +c.gen.int2+ c.phon+c.sem)*(Slope_Flanker_c+Slope_Simon_c+CTET_Hit_c+Span_Mean_c) +(1+c.gen.int1+c.gen.int2*Slope_Simon_c + c.phon+c.sem||Picture)+(1+c.gen.int1+c.gen.int2+ c.phon+c.sem||Participant_ID), data = df5[abs(scale(resid(m1)))<2.5,])
# print(summary(m1b, corr=F))

```

```{r Exp. 1 PWI}
# slope of pwi delta plot procedure----
df6 <- df2b %>%
  select(Participant_ID, Condition, RT) %>%
  filter(Condition %in% c("sem.unr", "sem.rel")) %>%
  mutate(compatible = ifelse(Condition == "sem.unr", "c", "i"))

inhib <- inhib.delta(rt = df6$RT, comp = df6$compatible, sujet = df6$Participant_ID, 
                     cond = NA, dquantile = 5, type = 7)

inhib_sem_all <- inhib[2]$delta.slope
colnames(inhib_sem_all)[1] <- "Participant_ID"

df7 <- merge(df2b, inhib_sem_all, by = "Participant_ID")

df8 <- droplevels(subset(df7, Condition %in% c("sem.rel", "sem.unr")))

contrasts(df8$Condition) <- c(-.5,.5)
m2 <- lmer(log(RT)~Condition*slope +(1+Condition+slope||Picture)+(1+Condition+slope||Participant_ID), data = df8)
summary(m2)

m2b <- lmer(log(RT)~Condition*slope +(1+Condition+slope||Picture)+(1+Condition+slope||Participant_ID), data = df8[abs(scale(resid(m2)))<2.5,])
print(summary(m2b, corr=F))

# raw RTs
m3 <- lmer(RT~Condition*slope +(1+Condition+slope||Picture)+(1+Condition+slope||Participant_ID), data = df8)
summary(m3)

m3b <- lmer(RT~Condition*slope +(1+Condition+slope||Picture)+(1+Condition+slope||Participant_ID), data = df8[abs(scale(resid(m2)))<2.5,])
print(summary(m3b, corr=F))

detach(package:plyr)
df9 <- df8 %>%
  select(Participant_ID, Condition, RT, slope) %>%
  group_by(Participant_ID, Condition, slope) %>%
  summarize(mean = mean(RT)) %>%
  pivot_wider(names_from = Condition, values_from = mean) %>%
  mutate(sem_int = sem.rel-sem.unr)

ggplot(df9, aes(slope, sem_int)) +
  geom_point() +
  geom_smooth(method = "lm")

cor.test(df9$slope, df9$sem_int)
```

# Experiment 2: PWI slope and magnitude of interference effect in fast and slow blocks
```{r prepare data Exp.2, include = FALSE}
# Experiment 2----
setwd("/Users/pamelafuhrmeister/Documents/Work/Postdoc/SFB/Experiment_2/Data")

df <- read.csv("Experiment_2_data.csv", sep=",")

df$Span_Mean_c <- df$Mean_Span_PCU-mean(df$Mean_Span_PCU)
df$CTET_Hit_c <- df$CTET_Hit_rate-mean(df$CTET_Hit_rate)
df$Slope_Simon_c <- df$Simon_Slope-mean(df$Simon_Slope)
df$Slope_Flanker_c <- df$Flanker_Slope-mean(df$Flanker_Slope)

summary(df)
df$Accuracy <- as.factor(as.character(df$Response_Trial))
df$Participant_ID <- as.factor(as.character(df$Participant_ID))

df$Picture  <- as.factor(as.character(df$Picture_ID))

df$Comment <- as.factor(as.character(df$Response_Trial))
df$Condition <- as.factor(as.character(df$Condition_ID))
df$Condition <- plyr::mapvalues(df$Condition, from = c("9001", "9002", "9003","9004","9005"), to = c("baseline","phono.rel", "phono.unr", "sem.rel", "sem.unr"))
df$Condition <- as.factor(as.character(df$Condition))

nrow(df)

table(df$Response_Trial)

df1 <- df %>%
  filter(Response_Trial == "correct", RT != "NA")

nrow(df1)
nrow(df) - nrow(df1)

# df2 <- df1[df1$RT>599,]
# 
# plot(density(df1$RT))
# qqnorm(df2$RT)
# hist(df2$RT)
# boxplot(df2$RT)
# 
# 
# df3 <- df2[df2$RT<2301,] 
# nrow(df2) - nrow(df3)

```

```{r}
df2 <- droplevels(subset(df1, Condition %in% c("sem.rel", "sem.unr")))
df2$Speed <- ifelse(df2$Type_Speed == 3001, "normal", "fast")

# all trials
contrasts(df2$Condition) <- c(-.5,.5)
m2 <- lmer(log(RT)~Condition*Slope_PWI_Sem_All_Speed +(1+Condition*Slope_PWI_Sem_All_Speed||Picture)+(1+Condition*Slope_PWI_Sem_All_Speed||Participant_ID), data = df2)
summary(m2)

m2b <- lmer(log(RT)~Condition*Slope_PWI_Sem_All_Speed +(1+Condition+Slope_PWI_Sem_All_Speed||Picture)+(1+Condition+Slope_PWI_Sem_All_Speed||Participant_ID), data = df2[abs(scale(resid(m2)))<2.5,])
print(summary(m2b, corr=F))

m3 <- lmer(RT~Condition*Slope_PWI_Sem_All_Speed +(1+Condition+Slope_PWI_Sem_All_Speed||Picture)+(1+Condition+Slope_PWI_Sem_All_Speed||Participant_ID), data = df2)
summary(m3)

m3b <- lmer(RT~Condition*Slope_PWI_Sem_All_Speed +(1+Condition+Slope_PWI_Sem_All_Speed||Picture)+(1+Condition+Slope_PWI_Sem_All_Speed||Participant_ID), data = df2[abs(scale(resid(m3)))<2.5,])
print(summary(m3b, corr=F))

df2a <- df2 %>%
  select(Participant_ID, Condition, RT, Slope_PWI_Sem_All_Speed) %>%
  group_by(Participant_ID, Condition, Slope_PWI_Sem_All_Speed) %>%
  summarize(mean = mean(RT)) %>%
  pivot_wider(names_from = Condition, values_from = mean) %>%
  mutate(sem_int = sem.rel-sem.unr)

ggplot(df2a, aes(Slope_PWI_Sem_All_Speed, sem_int)) +
  geom_point() +
  geom_smooth(method = "lm")

# fast trials
df3 <- droplevels(subset(df2, Speed == "fast"))
contrasts(df3$Condition) <- c(-.5,.5)

m4 <- lmer(log(RT)~Condition*Slope_PWI_Sem_Fast +(1+Condition+Slope_PWI_Sem_Fast||Picture)+(1+Condition+Slope_PWI_Sem_Fast||Participant_ID), data = df3)
summary(m4)

m4b <- lmer(log(RT)~Condition*Slope_PWI_Sem_Fast +(1+Condition+Slope_PWI_Sem_Fast||Picture)+(1+Condition+Slope_PWI_Sem_Fast||Participant_ID), data = df3[abs(scale(resid(m4)))<2.5,])
print(summary(m4b, corr=F))

m5 <- lmer(RT~Condition*Slope_PWI_Sem_Fast +(1+Condition+Slope_PWI_Sem_Fast||Picture)+(1+Condition+Slope_PWI_Sem_Fast||Participant_ID), data = df3)
summary(m5)

m5b <- lmer(RT~Condition*Slope_PWI_Sem_Fast +(1+Condition+Slope_PWI_Sem_Fast||Picture)+(1+Condition+Slope_PWI_Sem_Fast||Participant_ID), data = df3[abs(scale(resid(m5)))<2.5,])
print(summary(m5b, corr=F))

df3a <- df3 %>%
  select(Participant_ID, Condition, RT, Slope_PWI_Sem_Fast) %>%
  group_by(Participant_ID, Condition, Slope_PWI_Sem_Fast) %>%
  summarize(mean = mean(RT)) %>%
  pivot_wider(names_from = Condition, values_from = mean) %>%
  mutate(sem_int = sem.rel-sem.unr)

ggplot(df3a, aes(Slope_PWI_Sem_Fast, sem_int)) +
  geom_point() +
  geom_smooth(method = "lm")

# slow trials
df4 <- droplevels(subset(df2, Speed == "normal"))
contrasts(df4$Condition) <- c(-.5,.5)

m6 <- lmer(log(RT)~Condition*Slope_PWI_Sem_Constant +(1+Condition+Slope_PWI_Sem_Constant||Picture)+(1+Condition+Slope_PWI_Sem_Constant||Participant_ID), data = df4)
summary(m6)

m6b <- lmer(log(RT)~Condition*Slope_PWI_Sem_Constant +(1+Condition+Slope_PWI_Sem_Constant||Picture)+(1+Condition+Slope_PWI_Sem_Constant||Participant_ID), data = df4[abs(scale(resid(m6)))<2.5,])
print(summary(m6b, corr=F))

m7 <- lmer(RT~Condition*Slope_PWI_Sem_Constant +(1+Condition+Slope_PWI_Sem_Constant||Picture)+(1+Condition+Slope_PWI_Sem_Constant||Participant_ID), data = df4)
summary(m7)

m7b <- lmer(RT~Condition*Slope_PWI_Sem_Constant +(1+Condition+Slope_PWI_Sem_Constant||Picture)+(1+Condition+Slope_PWI_Sem_Constant||Participant_ID), data = df4[abs(scale(resid(m7)))<2.5,])
print(summary(m7b, corr=F))

df4a <- df4 %>%
  select(Participant_ID, Condition, RT, Slope_PWI_Sem_Constant) %>%
  group_by(Participant_ID, Condition, Slope_PWI_Sem_Constant) %>%
  summarize(mean = mean(RT)) %>%
  pivot_wider(names_from = Condition, values_from = mean) %>%
  mutate(sem_int = sem.rel-sem.unr)

ggplot(df4a, aes(Slope_PWI_Sem_Constant, sem_int)) +
  geom_point() +
  geom_smooth(method = "lm")

```

